name: CI/CD - Deploy to EC2 (No PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Node-API/CRUD/Backend
            git pull origin main
            npm install
            pkill -f "node index.js" || true
            nohup node index.js > output.log 2>&1 &
